import type { CompiledScript, PlayerState, TpsPlaybackEventMap, TpsPlaybackEventName, TpsPlaybackSessionOptions, TpsPlaybackSnapshot, TpsPlaybackStatus } from "./models.js";
import { TpsPlayer } from "./player.js";
export declare class TpsPlaybackSession {
    private readonly blockIndexById;
    private readonly blocks;
    private readonly listeners;
    private readonly now;
    private readonly segmentIndexById;
    private readonly tickIntervalMs;
    private playbackOffsetMs;
    private playbackStartedAtMs;
    private speedOffsetWpm;
    private timer;
    readonly baseWpm: number;
    readonly player: TpsPlayer;
    readonly speedStepWpm: number;
    currentState: PlayerState;
    status: TpsPlaybackStatus;
    constructor(scriptOrPlayer: CompiledScript | TpsPlayer, options?: TpsPlaybackSessionOptions);
    get effectiveBaseWpm(): number;
    get isPlaying(): boolean;
    get playbackRate(): number;
    get snapshot(): TpsPlaybackSnapshot;
    get speedOffset(): number;
    on<K extends TpsPlaybackEventName>(eventName: K, listener: (event: TpsPlaybackEventMap[K]) => void): () => void;
    off<K extends TpsPlaybackEventName>(eventName: K, listener: (event: TpsPlaybackEventMap[K]) => void): void;
    observeSnapshot(listener: (snapshot: TpsPlaybackSnapshot) => void, emitCurrent?: boolean): () => void;
    play(): PlayerState;
    pause(): PlayerState;
    stop(): PlayerState;
    seek(elapsedMs: number): PlayerState;
    advanceBy(deltaMs: number): PlayerState;
    nextWord(): PlayerState;
    previousWord(): PlayerState;
    nextBlock(): PlayerState;
    previousBlock(): PlayerState;
    increaseSpeed(stepWpm?: number): TpsPlaybackSnapshot;
    decreaseSpeed(stepWpm?: number): TpsPlaybackSnapshot;
    setSpeedOffsetWpm(offsetWpm: number): TpsPlaybackSnapshot;
    createSnapshot(): TpsPlaybackSnapshot;
    dispose(): void;
    private changeSpeedBy;
    private createControls;
    private emit;
    private emitSnapshotChanged;
    private scheduleNextTick;
    private readLiveElapsedMs;
    private updatePosition;
    private updateStatus;
    private clearTimer;
}
